//
//  AutoGeneratedTests.swift
//
//
//  Created by Hugh Bellamy on 16/09/2020.
//

import DataStream
import XCTest
import MAPI
@testable import PstReader

final class AutoGeneratedTests: XCTestCase {
    func test() throws {
        let data = try getData(name: "backup")
        let pst = try PstFile(data: data)
        XCTAssertNotNil(pst)
    }
}
